## =============================================================================
## Writes the LaTeX tables of the manuscript from results/*.csv, so that every
## number in a table is the number the simulation produced.
##
##   Rscript R/make_tables.R        ->  manuscript/tables/*.tex
##
## Each file holds a complete tabular environment (booktabs); body.tex supplies
## the table environment, caption and label. Base R only.
## =============================================================================

here <- local({
  f <- sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE))
  if (length(f)) dirname(normalizePath(f)) else "R"
})
root <- dirname(here)
source(file.path(here, "bscme_methods.R"))
source(file.path(here, "scenarios.R"))
res_dir <- file.path(root, "results")
tab_dir <- file.path(root, "manuscript", "tables")
dir.create(tab_dir, recursive = TRUE, showWarnings = FALSE)

rd  <- function(f) read.csv(file.path(res_dir, f), stringsAsFactors = FALSE)
fmt <- function(x, d = 2) ifelse(is.na(x), "--", formatC(x, format = "f", digits = d))
fmt_n1 <- function(x) ifelse(is.finite(x), formatC(round(x), format = "d"), paste0("$>$", max(n1_grid)))
fmt_ratio <- function(s) {                      # "0.42", "<0.34", ">3.01" or NA
  s <- as.character(s)
  ifelse(is.na(s) | s == "", "", gsub("^([<>])", "$\\1$", s))
}
fmt_theta <- function(x) ifelse(x < 0, sprintf("$%.2f$", x), sprintf("%.2f", x))
design_label <- c(M = "M: co-primary gate",
                  Cu = "C: composite, uniform $\\mathbf w$",
                  Cj = "C: composite, $\\mathbf w^\\star(\\Theta_{\\mathrm{all}})$",
                  Cc_S3 = "C: composite, $\\mathbf w^\\star$(S3)",
                  Cc_S4 = "C: composite, $\\mathbf w^\\star$(S4)")
cfg_label <- c(config_labels, null_labels)
with_se <- function(x, se, d = 0) ifelse(is.na(se), fmt(x, d), paste0(fmt(x, d), " (", fmt(se, 1), ")"))

emit <- function(name, header, rows, footer = "\\bottomrule\n\\end{tabular}") {
  txt <- c("%% Generated by R/make_tables.R from results/*.csv; do not edit by hand.",
           header, rows, footer)
  writeLines(txt, file.path(tab_dir, paste0(name, ".tex")))
  cat("wrote", file.path("manuscript/tables", paste0(name, ".tex")), "\n")
}
row <- function(...) paste(paste(..., sep = " & "), "\\\\")
first_only <- function(x) ifelse(duplicated(x), "", x)

## ---------------------------------------------------------------- tab:scen
rows <- unlist(lapply(names(configs), function(s) {
  th <- configs[[s]]; M <- nrow(th)
  opt <- optimal_dose(th); copt <- composite_optimal_dose(th, w_uniform)
  r <- vapply(seq_len(M), function(a)
    row(if (a == 1) cfg_label[s] else "", a, paste(fmt_theta(th[a, ]), collapse = " & "),
        if (a == 1) opt else "", if (a == 1) copt else ""), character(1))
  c(r, if (s != names(configs)[length(configs)]) "\\addlinespace[3pt]")
}))
emit("tab_scen",
     c("\\begin{tabular}{llcccccc}", "\\toprule",
       "& & \\multicolumn{4}{c}{$\\theta_{a,k}$, endpoints $k=1,\\dots,4$} & Optimal & Composite-optimal \\\\",
       "\\cmidrule(lr){3-6}",
       "Configuration & Dose & 1 & 2 & 3 & 4 & dose & (uniform $\\bw$) \\\\", "\\midrule"),
     rows)

## --------------------------------------------------------------- tab:nulls
rows <- unlist(lapply(names(null_configs), function(s) {
  th <- null_configs[[s]]; M <- nrow(th)
  r <- vapply(seq_len(M), function(a)
    row(if (a == 1) cfg_label[s] else "", a, paste(fmt_theta(th[a, ]), collapse = " & ")), character(1))
  c(r, if (s != names(null_configs)[length(null_configs)]) "\\addlinespace[3pt]")
}))
emit("tab_nulls",
     c("\\begin{tabular}{llcccc}", "\\toprule",
       "& & \\multicolumn{4}{c}{$\\theta_{a,k}$, endpoints $k=1,\\dots,4$} \\\\",
       "\\cmidrule(lr){3-6}",
       "Configuration & Dose & 1 & 2 & 3 & 4 \\\\", "\\midrule"),
     rows)

## ------------------------------------------------------------- tab:weights
w <- rd("weights_calibrated.csv")
w <- w[order(match(w$cfg, names(configs)), w$rho), ]
rows <- row(first_only(cfg_label[w$cfg]), fmt(w$rho, 1),
            fmt(w$w1, 2), fmt(w$w2, 2), fmt(w$w3, 2), fmt(w$w4, 2),
            paste(ifelse(w$concordant_uniform, "yes", "no"), "/",
                  ifelse(w$concordant_calibrated, "yes", "no")))
emit("tab_weights",
     c("\\begin{tabular}{llccccc}", "\\toprule",
       "& & \\multicolumn{4}{c}{$\\bw^\\star$} & Concordant \\\\", "\\cmidrule(lr){3-6}",
       "Configuration & $\\rho_{\\mathrm{lat}}$ & $w_1$ & $w_2$ & $w_3$ & $w_4$ & uniform / calibrated \\\\",
       "\\midrule"),
     rows)

## ---------------------------------------------------------------- tab:main
tm <- rd("table_main_n1.csv"); br <- rd("bracket.csv")
tm <- tm[order(match(tm$cfg, names(configs)), tm$rho), ]
tm$phi <- br$phi[match(tm$rho, br$rho_latent)]
tm$conc <- paste(ifelse(w$concordant_uniform[match(paste(tm$cfg, tm$rho), paste(w$cfg, w$rho))], "yes", "no"), "/",
                 ifelse(w$concordant_calibrated[match(paste(tm$cfg, tm$rho), paste(w$cfg, w$rho))], "yes", "no"))
tm$bracket <- ifelse(tm$cfg == "S1",
                     sprintf("[%.2f, %.2f]", br$lower[match(tm$rho, br$rho_latent)],
                             br$upper[match(tm$rho, br$rho_latent)]), "")
n1_cell <- function(n, se) ifelse(is.finite(n), with_se(n, se), paste0("$>$", max(n1_grid)))
rows <- row(first_only(cfg_label[tm$cfg]), fmt(tm$rho, 1), fmt(tm$phi, 2), tm$conc,
            n1_cell(tm$n1_M, tm$se_M), n1_cell(tm$n1_Cu, tm$se_Cu), n1_cell(tm$n1_Cc, tm$se_Cc),
            fmt_ratio(tm$ratio_u), fmt_ratio(tm$ratio_c), tm$bracket)
emit("tab_main",
     c("\\setlength{\\tabcolsep}{3pt}", "\\begin{tabular}{llcccccccc}", "\\toprule",
       paste("Configuration & $\\rho_{\\mathrm{lat}}$ & $\\phi$ & Concordant & $n_1^{\\mathrm{M}}$ &",
             "$n_1^{\\mathrm{C,u}}$ & $n_1^{\\mathrm{C,c}}$ & $n_1^{\\mathrm{C,u}}/n_1^{\\mathrm{M}}$ &",
             "$n_1^{\\mathrm{C,c}}/n_1^{\\mathrm{M}}$ & Bracket \\eqref{eq:bracket} \\\\"),
       "\\midrule"),
     rows)
cat(sprintf("  tab_main SE range: conjunctive %.0f-%.0f, composite %.0f-%.0f subjects\n",
            min(tm$se_M, na.rm = TRUE), max(tm$se_M, na.rm = TRUE),
            min(c(tm$se_Cu, tm$se_Cc), na.rm = TRUE), max(c(tm$se_Cu, tm$se_Cc), na.rm = TRUE)))

## -------------------------------------------------------------- tab:msweep
ms <- rd("table_msweep.csv")
emit("tab_msweep",
     c("\\begin{tabular}{ccccc}", "\\toprule",
       "$M$ & $n_1^{\\mathrm{M}}$ & $n_1^{\\mathrm{C}}$ & Ratio & $\\Delta N$ \\\\", "\\midrule"),
     row(ms$M, with_se(ms$n1_M, ms$se_M), with_se(ms$n1_C, ms$se_C), fmt(ms$ratio, 2), ms$delta_N))

## -------------------------------------------------------------- tab:wjoint
wj <- rd("weights_joint.csv")
set_label <- c(all = "$\\Theta_{\\mathrm{all}}=\\{$S1, S2, S3, S4$\\}$",
               concordant = "$\\Theta_{\\mathrm{conc}}=\\{$S1, S2, S3$\\}$",
               all_floor = paste0("$\\Theta_{\\mathrm{all}}$, $w_k\\ge", fmt(w_floor, 2), "$"))
emit("tab_wjoint",
     c("\\begin{tabular}{lcccccc}", "\\toprule",
       "& \\multicolumn{4}{c}{$\\bw^\\star$} & \\multicolumn{2}{c}{Mean PCS over $\\Theta$} \\\\",
       "\\cmidrule(lr){2-5}\\cmidrule(lr){6-7}",
       "Scenario set $\\Theta$ (constraint) & $w_1$ & $w_2$ & $w_3$ & $w_4$ & composite $\\bw^\\star$ & co-primary gate \\\\",
       "\\midrule"),
     {
       cr <- rd("pcs_cross.csv")
       mean_pcs <- function(gate, set) mean(cr$pcs[cr$gate == gate & cr$cfg %in% theta_sets[[set]]])
       gate_of <- c(all = "Cj_all", concordant = "Cj_conc", all_floor = "Cj_floor")
       set_of <- c(all = "all", concordant = "concordant", all_floor = "all")
       row(set_label[wj$set], fmt(wj$w1, 2), fmt(wj$w2, 2), fmt(wj$w3, 2), fmt(wj$w4, 2),
           fmt(sapply(wj$set, function(s) mean_pcs(gate_of[s], set_of[s])), 3),
           fmt(sapply(wj$set, function(s) mean_pcs("M", set_of[s])), 3))
     })

## --------------------------------------------------------------- tab:cross
cr <- rd("pcs_cross.csv")
gates <- c("M", "Cu", "Cj_all", "Cj_conc", "Cj_floor", "Cc_S3", "Cc_S4")
gate_head <- c(M = "co-primary", Cu = "uniform", Cj_all = "$\\bw^\\star(\\Theta_{\\mathrm{all}})$",
               Cj_conc = "$\\bw^\\star(\\Theta_{\\mathrm{conc}})$",
               Cj_floor = "$\\bw^\\star(\\Theta_{\\mathrm{all}}, w_k\\ge0.1)$",
               Cc_S3 = "$\\bw^\\star$(S3)", Cc_S4 = "$\\bw^\\star$(S4)")
get <- function(cfg, gate, var) cr[[var]][cr$cfg == cfg & cr$gate == gate]
cells <- function(x) paste(x, collapse = " & ")
rows <- unlist(lapply(names(configs), function(s) {
  c(row(cfg_label[s], "PCS", cells(sapply(gates, function(g) fmt(get(s, g, "pcs"), 3)))),
    row("", "regret $\\times100$", cells(sapply(gates, function(g) fmt(100 * get(s, g, "regret"), 2)))))
}))
rows <- c(rows, "\\midrule",
          row("Mean PCS, S1--S4", "", cells(sapply(gates, function(g) fmt(mean(sapply(theta_sets$all, get, g, "pcs")), 3)))),
          row("Mean PCS, S1--S3", "", cells(sapply(gates, function(g) fmt(mean(sapply(theta_sets$concordant, get, g, "pcs")), 3)))))
emit("tab_cross",
     c("\\setlength{\\tabcolsep}{3pt}", "\\begin{tabular}{llccccccc}", "\\toprule",
       "& & \\multicolumn{1}{c}{Co-primary} & \\multicolumn{6}{c}{Composite gate, weights} \\\\",
       "\\cmidrule(lr){3-3}\\cmidrule(lr){4-9}",
       paste("Configuration & &", paste(gate_head[gates], collapse = " & "), "\\\\"), "\\midrule"),
     rows)

## ----------------------------------------------------------------- tab:eta
et <- rd("e2e_eta.csv")
et <- et[order(match(et$cfg, names(cfg_label)), et$target, match(et$design, names(design_label))), ]
rows <- unlist(lapply(unique(et$cfg), function(s) {
  d <- et[et$cfg == s, ]
  c(row(first_only(cfg_label[d$cfg]), fmt(d$target, 2), design_label[d$design], fmt(d$eta, 3),
        fmt(d$proceed, 3), fmt(d$pcs, 3),
        if (s %in% names(configs)) fmt(d$power, 3) else fmt(d$false_claim, 4), fmt(d$EN, 0)),
    if (s != tail(unique(et$cfg), 1)) "\\addlinespace[3pt]")
}))
emit("tab_eta",
     c("\\begin{tabular}{llcccccc}", "\\toprule",
       paste("Configuration & $\\Pr(\\text{proceed}\\mid\\text{N0})$ & Design & $\\eta$ &",
             "$\\Pr(\\text{proceed})$ & PCS & Power / false claim & $E[N]$ \\\\"),
       "\\midrule"),
     rows)

## ---------------------------------------------------------------- tab:e2eA
A <- rd("e2e_runA.csv")
alt <- A[A$cfg %in% names(configs), ]
wide <- function(d, vars, digits) {
  key <- unique(d[, c("cfg", "design")])
  key <- key[order(match(key$cfg, names(cfg_label)), match(key$design, names(design_label))), ]
  cells <- t(apply(key, 1, function(k) {
    unlist(lapply(rho_latent, function(r) {
      z <- d[d$cfg == k[["cfg"]] & d$design == k[["design"]] & d$rho == r, ]
      mapply(function(v, dg) fmt(z[[v]], dg), vars, digits)
    }))
  }))
  list(key = key, cells = cells)
}
wa <- wide(alt, c("pcs", "power", "EN"), c(2, 2, 0))
rows <- unlist(lapply(unique(wa$key$cfg), function(s) {
  i <- which(wa$key$cfg == s)
  c(row(first_only(cfg_label[wa$key$cfg[i]]), design_label[wa$key$design[i]],
        apply(wa$cells[i, , drop = FALSE], 1, paste, collapse = " & ")),
    if (s != tail(unique(wa$key$cfg), 1)) "\\addlinespace[3pt]")
}))
emit("tab_e2eA",
     c("\\setlength{\\tabcolsep}{3.5pt}", "\\begin{tabular}{llccccccccc}", "\\toprule",
       paste("& &", paste(sprintf("\\multicolumn{3}{c}{$\\rho_{\\mathrm{lat}}=%s$}", fmt(rho_latent, 1)),
                          collapse = " & "), "\\\\"),
       "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}\\cmidrule(lr){9-11}",
       "Configuration & Design & PCS & Power & $E[N]$ & PCS & Power & $E[N]$ & PCS & Power & $E[N]$ \\\\",
       "\\midrule"),
     rows)
cat(sprintf("  max false-claim rate in run A alternatives: %.4f (%s)\n",
            max(alt$false_claim), paste(unique(alt$cfg[alt$false_claim == max(alt$false_claim)]), collapse = ",")))

## ---------------------------------------------------------------- tab:e2eN
nul <- A[A$cfg %in% names(null_configs), ]
wn <- wide(nul, c("proceed", "false_claim"), c(2, 4))
# reorder the cells so that the three proceed columns come first, then false claims
ord <- c(1, 3, 5, 2, 4, 6)
rows <- unlist(lapply(unique(wn$key$cfg), function(s) {
  i <- which(wn$key$cfg == s)
  c(row(first_only(cfg_label[wn$key$cfg[i]]), design_label[wn$key$design[i]],
        apply(wn$cells[i, ord, drop = FALSE], 1, paste, collapse = " & ")),
    if (s != tail(unique(wn$key$cfg), 1)) "\\addlinespace[3pt]")
}))
emit("tab_e2eN",
     c("\\setlength{\\tabcolsep}{4pt}", "\\begin{tabular}{llcccccc}", "\\toprule",
       "& & \\multicolumn{3}{c}{$\\Pr(\\text{proceed})$} & \\multicolumn{3}{c}{$\\Pr(\\text{false claim})$} \\\\",
       "\\cmidrule(lr){3-5}\\cmidrule(lr){6-8}",
       "Configuration & Design & $\\rho_{\\mathrm{lat}}=0$ & $0.3$ & $0.6$ & $\\rho_{\\mathrm{lat}}=0$ & $0.3$ & $0.6$ \\\\",
       "\\midrule"),
     rows)
cat(sprintf("  max false-claim rate in run A nulls: %.4f (%s)\n",
            max(nul$false_claim), paste(unique(nul$cfg[nul$false_claim == max(nul$false_claim)]), collapse = ",")))

## ------------------------------------------------------------- tab:closure
cl <- rd("e2e_closure.csv")
qty <- c(S1 = "power", S3 = "power", N1 = "false_claim", N3 = "false_claim")
qty <- c(qty, N4 = "false_claim")
key <- expand.grid(design = c("M", "Cu"), cfg = c("N1", "N3", "N4", "S1", "S3"), stringsAsFactors = FALSE)[, 2:1]
cells <- t(apply(key, 1, function(k) {
  unlist(lapply(rho_latent, function(r) {
    vapply(c("endpoint", "union"), function(cz) {
      z <- cl[cl$cfg == k[["cfg"]] & cl$design == k[["design"]] & cl$rho == r & cl$closure == cz, ]
      fmt(z[[qty[k[["cfg"]]]]], if (qty[k[["cfg"]]] == "power") 3 else 4)
    }, character(1))
  }))
}))
rows <- unlist(lapply(unique(key$cfg), function(s) {
  i <- which(key$cfg == s)
  c(row(first_only(cfg_label[key$cfg[i]]),
        ifelse(qty[key$cfg[i]] == "power", "power", "false claim"),
        design_label[key$design[i]],
        apply(cells[i, , drop = FALSE], 1, paste, collapse = " & ")),
    if (s != tail(unique(key$cfg), 1)) "\\addlinespace[3pt]")
}))
emit("tab_closure",
     c("\\setlength{\\tabcolsep}{3.5pt}", "\\begin{tabular}{lllcccccc}", "\\toprule",
       paste("& & &", paste(sprintf("\\multicolumn{2}{c}{$\\rho_{\\mathrm{lat}}=%s$}", fmt(rho_latent, 1)),
                            collapse = " & "), "\\\\"),
       "\\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(lr){8-9}",
       "Configuration & Quantity & Design & per endpoint & union & per endpoint & union & per endpoint & union \\\\",
       "\\midrule"),
     rows)

## ---------------------------------------------------------------- tab:e2eB
B <- rd("e2e_runB.csv")
B <- B[order(match(B$cfg, names(configs)), B$rho, match(B$design, names(design_label))), ]
rows <- unlist(lapply(unique(B$cfg), function(s) {
  d <- B[B$cfg == s, ]
  c(row(first_only(cfg_label[d$cfg]), fmt(d$rho, 1), design_label[d$design], d$n1,
        fmt(d$proceed, 3), fmt(d$pcs, 3), fmt(d$power, 3), fmt(d$EN, 0)),
    if (s != tail(unique(B$cfg), 1)) "\\addlinespace[3pt]")
}))
emit("tab_e2eB",
     c("\\begin{tabular}{llcccccc}", "\\toprule",
       "Configuration & $\\rho_{\\mathrm{lat}}$ & Design & $n_1$ & $\\Pr(\\text{proceed})$ & PCS & Power & $E[N]$ \\\\",
       "\\midrule"),
     rows)

## ---------------------------------------------------------------- tab:e2eC
C <- rd("e2e_runC.csv")
rows <- unlist(lapply(c("S1", "S3"), function(s) {
  d <- C[C$cfg == s, ]
  r <- vapply(sort(unique(d$n1)), function(n) {
    m <- d[d$n1 == n & d$design == "M", ]; cc <- d[d$n1 == n & d$design != "M", ]
    row(if (n == min(d$n1)) cfg_label[s] else "", n,
        fmt(m$proceed, 3), fmt(m$pcs, 3), fmt(m$power, 3), fmt(m$EN, 0),
        fmt(cc$proceed, 3), fmt(cc$pcs, 3), fmt(cc$power, 3), fmt(cc$EN, 0))
  }, character(1))
  c(r, if (s != "S3") "\\addlinespace[3pt]")
}))
emit("tab_e2eC",
     c("\\setlength{\\tabcolsep}{4pt}", "\\begin{tabular}{lccccccccc}", "\\toprule",
       "& & \\multicolumn{4}{c}{M: co-primary gate} & \\multicolumn{4}{c}{C: composite gate} \\\\",
       "\\cmidrule(lr){3-6}\\cmidrule(lr){7-10}",
       paste("Configuration & $n_1$ & $\\Pr(\\text{proceed})$ & PCS & Power & $E[N]$ &",
             "$\\Pr(\\text{proceed})$ & PCS & Power & $E[N]$ \\\\"),
       "\\midrule"),
     rows)

## --------------------------------------------------------------- tab:e2eCm
Cm <- rd("e2e_runC_matched.csv")
rows <- unlist(lapply(c("S1", "S3"), function(s) {
  d <- Cm[Cm$cfg == s, ]
  c(row(first_only(cfg_label[d$cfg]), fmt(d$target, 2),
        with_se(d$n1_M, d$se_n1_M), with_se(d$EN_M, d$se_EN_M),
        with_se(d$n1_C, d$se_n1_C), with_se(d$EN_C, d$se_EN_C),
        ifelse(is.na(d$ratio), "--", paste0(fmt(d$ratio, 2), " (", fmt(d$se_ratio, 3), ")"))),
    if (s != "S3") "\\addlinespace[3pt]")
}))
emit("tab_e2eCm",
     c("\\begin{tabular}{lcccccc}", "\\toprule",
       "& & \\multicolumn{2}{c}{M: co-primary gate} & \\multicolumn{2}{c}{C: composite gate} & \\\\",
       "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}",
       "Configuration & Target power & $n_1$ & $E[N]$ & $n_1$ & $E[N]$ & $E[N]$ ratio C/M \\\\",
       "\\midrule"),
     rows)
